#!/usr/bin/env bash
read -r URL


if [[ "$URL" != "localhost:1447" ]]; then 
    echo "expected registry url to be localhost:1447";
    exit 1
fi

echo "{\"ServerURL\": \"$URL\", \"Username\": \"testing\", \"Secret\": \"oci\"}"